name: Update Bevelgacom Deployment

on:
  push:
    branches:
      - main

jobs:
  update-bevelgacom:
    runs-on: self-hosted

    steps:
    - name: Pull latest changes
      run: |
        cd /var/www/wapfind
        sudo git pull origin main